/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bftsmart_optilog_PrecisionClock_PTPClock */

#ifndef _Included_bftsmart_optilog_PrecisionClock_PTPClock
#define _Included_bftsmart_optilog_PrecisionClock_PTPClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bftsmart_optilog_PrecisionClock_PTPClock
 * Method:    getPTPTimestamp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bftsmart_optilog_PrecisionClock_PTPClock_getPTPTimestamp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
